"""
Django settings for keymgmt project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# True while the Django test runner is active (`manage.py test`) — used to relax
# production-only guards so the suite runs without secrets or the login gate.
TESTING = "test" in sys.argv

_INSECURE_KEY = "django-insecure-din5tgy(39ctgy+=lr67!d4v*_&86+fl0uplqcmc7_wi%ltfrl"


def _env(key, default=None):
    return os.environ.get(key, default)


def _env_bool(key, default):
    val = os.environ.get(key)
    return default if val is None else val.strip().lower() in ("1", "true", "yes", "on")


def _env_list(key, default=""):
    return [x.strip() for x in os.environ.get(key, default).split(",") if x.strip()]


# SECURITY: keep the secret key secret. In production set KEYMGMT_SECRET_KEY, or
# point KEYMGMT_SECRET_KEY_FILE at a file (e.g. an agenix/sops secret).
def _secret_key():
    if val := _env("KEYMGMT_SECRET_KEY"):
        return val
    path = _env("KEYMGMT_SECRET_KEY_FILE")
    if path and Path(path).exists():
        return Path(path).read_text().strip()
    return _INSECURE_KEY


SECRET_KEY = _secret_key()

# SECURITY: DEBUG is OFF by default. For local development run e.g.
#   KEYMGMT_DEBUG=1 uv run python manage.py runserver
DEBUG = _env_bool("KEYMGMT_DEBUG", False)

# Refuse to start a real deployment on the shipped insecure key.
if not DEBUG and not TESTING and SECRET_KEY == _INSECURE_KEY:
    raise ImproperlyConfigured(
        "Set KEYMGMT_SECRET_KEY (or KEYMGMT_SECRET_KEY_FILE) for a non-DEBUG "
        "deployment — refusing to run with the built-in insecure key.")

# Hosts allowed to serve the app (comma-separated). Behind nginx this is your
# domain; loopback is kept for local health checks.
ALLOWED_HOSTS = _env_list("KEYMGMT_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]")

# Origins trusted for unsafe (POST) requests — required behind an HTTPS proxy,
# e.g. KEYMGMT_CSRF_TRUSTED_ORIGINS=https://schliessmatrix.example.org
CSRF_TRUSTED_ORIGINS = _env_list("KEYMGMT_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'access',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'keymgmt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'keymgmt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _env("KEYMGMT_DB_PATH", str(BASE_DIR / 'db.sqlite3')),
        # SQLite concurrency: wait (don't error) on a locked DB, and take the
        # write lock up front so atomic blocks can't deadlock mid-way. WAL and
        # the other pragmas are set per-connection in access/apps.py.
        'OPTIONS': {
            'timeout': 15,
            'transaction_mode': 'IMMEDIATE',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = _env("KEYMGMT_LANGUAGE_CODE", "de")

TIME_ZONE = _env("KEYMGMT_TIME_ZONE", "Europe/Berlin")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Authentication: gate the whole UI behind a login ----------------------
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Require login for every page (default: on, off during tests). Turn off only
# if a trusted auth proxy sits in front (e.g. Authelia via nginx auth_request).
REQUIRE_LOGIN = _env_bool("KEYMGMT_REQUIRE_LOGIN", not TESTING)
if REQUIRE_LOGIN:
    MIDDLEWARE.append("django.contrib.auth.middleware.LoginRequiredMiddleware")


# --- Hardening for a reverse-proxy (nginx) deployment ----------------------
# nginx terminates TLS and must forward the scheme:
#   proxy_set_header X-Forwarded-Proto $scheme;
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
_SECURE = not DEBUG and not TESTING
SESSION_COOKIE_SECURE = _SECURE
CSRF_COOKIE_SECURE = _SECURE
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
# HSTS is best owned by nginx; set KEYMGMT_HSTS_SECONDS to also emit it here.
SECURE_HSTS_SECONDS = int(_env("KEYMGMT_HSTS_SECONDS", "0") or "0") if _SECURE else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("KEYMGMT_HSTS_SUBDOMAINS", False)
