# Generated by Django 5.2.15 on 2026-06-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('serial', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('door_name', models.CharField(blank=True, max_length=255)),
                ('room_number', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('area', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['location', 'door_name', 'serial'],
            },
        ),
        migrations.CreateModel(
            name='Transponder',
            fields=[
                ('serial', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('asta_number', models.IntegerField(blank=True, null=True)),
                ('person_name', models.CharField(blank=True, max_length=255)),
                ('locking_system', models.CharField(blank=True, max_length=64)),
                ('printed_on', models.DateField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('locks', models.ManyToManyField(blank=True, related_name='transponders', to='access.lock')),
            ],
            options={
                'ordering': ['asta_number', 'person_name', 'serial'],
            },
        ),
    ]
