# Generated by Django 6.0.6 on 2026-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transponder',
            name='planned_locks',
            field=models.ManyToManyField(blank=True, related_name='planned_transponders', to='access.lock'),
        ),
    ]
