# Generated by Django 6.0.6 on 2026-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_transponder_planned_locks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transponder',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
