# Generated by Django 6.0.6 on 2026-07-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_transponder_imported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transponder',
            name='desired_locks',
            field=models.ManyToManyField(blank=True, related_name='desired_transponders', to='access.lock'),
        ),
    ]
