# Generated by Django 6.0.6 on 2026-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_transponder_desired_locks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('doors', models.ManyToManyField(blank=True, related_name='groups', to='access.lock')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transponder',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='transponders', to='access.group'),
        ),
    ]
