# Generated by Django 6.0.6 on 2026-07-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_group_transponder_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='transponder',
            name='removed_locks',
            field=models.ManyToManyField(blank=True, related_name='removed_transponders', to='access.lock'),
        ),
    ]
